version: "3.3"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "python wait_for_postgres.py &&
                      ./manage.py migrate &&
                      ./manage.py runserver 0.0.0.0:8000"
    container_name: web
    depends_on:
      - database
    env_file: env/web.env
    ports:
    - 8000:8000
    volumes:
      - ./:/home/user/app
  database:
    container_name: postgres
    env_file: env/database.env
    image: postgres:13.2
    volumes:
      - .db:/var/lib/postgresql/data
